config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/auth/:provider', to: 'auth#request', as: :auth_request
  get '/auth/:provider/callback', to: 'web/auth#callback', as: :callback_auth

  scope module: :web do
    resources :sessions, only: :destroy
    root 'bulletins#index'
    resources :bulletins do
      member do
        patch 'to_moderate'
        patch 'archive'
      end
    end
    namespace 'admin' do
      root 'bulletins#index'
      resources :bulletins do
        member do
          patch 'to_moderate'
          patch 'publish'
          patch 'archive'
          patch 'reject'
        end
      end
      resources :categories
      resources :users
    end
    get 'profile', to: 'profile#index'
  end
end

app/controllers/web/profile_controller.rb
# frozen_string_literal: true

class Web::ProfileController < Web::ApplicationController
  before_action :authenticate_user!
  def index
    # @bulletins = Bulletin.order(created_at: :desc).where(user_id: current_user.id).page params[:page]
    @bulletins = current_user.bulletins.order(created_at: :desc).page(params[:page])
  end
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/views/web/profile/index.html.slim
.mb-4
  h2 = t('bulletins.my_bulletins')
  hr
table.table
  thead
    tr
    tr
      th scope="col" = t('activerecord.attributes.bulletin.title')
      th scope="col" = t('activerecord.attributes.bulletin.state')
      th scope="col" = t('activerecord.attributes.bulletin.created_at')
      th scope="col" = t('actions')
  tbody
    - @bulletins.each do |bulletin|
      tr
        td = link_to bulletin.title, bulletin_path(bulletin)
        td = bulletin.state
        td = time_ago_in_words(bulletin.created_at)
        td
          = link_to t('edit'), edit_bulletin_path(bulletin), class: 'link-primary me-2'
          - if bulletin.may_moderate?
            = link_to t('bulletins.state.events.to_moderate'), to_moderate_bulletin_path(bulletin), method: :patch, class: 'link-primary me-2'
          - if bulletin.may_archive?
            = link_to t('bulletins.state.events.archive'), archive_bulletin_path(bulletin), method: :patch, class: 'link-primary me-2'
          = link_to t('delete'), bulletin_path(bulletin), method: :delete, class: 'link-danger'
= paginate @bulletins