config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/auth/:provider', to: 'auth#request', as: :auth_request
  get '/auth/:provider/callback', to: 'web/auth#callback', as: :callback_auth

  scope module: :web do
    resources :sessions, only: :destroy
    root 'bulletins#index'
    resources :bulletins do
      member do
        patch 'to_moderate'
        patch 'archive'
      end
    end
    namespace 'admin' do
      root 'bulletins#index'
      resources :bulletins do
        member do
          patch 'to_moderate'
          patch 'publish'
          patch 'archive'
          patch 'reject'
        end
      end
      resources :categories
      resources :users
    end
    get 'profile', to: 'profile#index'
  end
end

app/views/layouts/shared/_flash.html.slim
- alert_class = flash.notice ? 'success' : 'danger'
div class="alert alert-#{alert_class} alert-dismissible fade show" role="alert"
  span = flash.notice || flash.alert
  button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"

app/views/layouts/shared/_header.html.slim
.d-flex.flex-wrap.align-items-center.py-2.border-bottom
  .navbar.navbar-expand-md.navbar-light.me-auto
    = link_to t('title'), root_path, class: 'navbar-brand me-md-4'
    div id='navbarToggler' class='collapse navbar-collapse'
      ul class='nav nav-pills flex-grow-1 navbar-nav me-auto'
        li.nav-item.me-2
          = link_to t('home'), root_path, class: 'nav-link text-dark'
        - if current_user
          li.nav-item.me-2
            = link_to t('bulletins.my_bulletins'), profile_path, class: 'nav-link text-dark'
          li.nav-item.me-2
            = link_to t('bulletins.create'), new_bulletin_path, class: 'nav-link text-dark'
  ul.nav.nav-pills
    - if current_user&.admin?
      li.nav-item.me-2
        = link_to t('admin'), admin_root_path, class: 'nav-link text-dark'
    - if current_user
      li.nav-item.me-2
        = link_to t('session.logout'), session_path(session.id), method: :delete, class: 'nav-link text-dark'
    - else
      li.nav-item.me-2
        = link_to t('session.signin'), auth_request_path(:github), method: :post, class: 'nav-link text-dark'