config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/auth/:provider', to: 'auth#request', as: :auth_request
  get '/auth/:provider/callback', to: 'web/auth#callback', as: :callback_auth

  scope module: :web do
    resources :sessions, only: :destroy
    root 'bulletins#index'
    resources :bulletins do
      member do
        patch 'to_moderate'
        patch 'archive'
      end
    end
    namespace 'admin' do
      root 'bulletins#index'
      resources :bulletins do
        member do
          patch 'to_moderate'
          patch 'publish'
          patch 'archive'
          patch 'reject'
        end
      end
      resources :categories
      resources :users
    end
    get 'profile', to: 'profile#index'
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  aasm column: 'state' do
    state :draft, initial: true
    state :under_moderation
    state :published
    state :rejected
    state :archived

    event :moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %w[draft under_moderation published rejected], to: :archived
    end
  end
  belongs_to :category
  belongs_to :user
  has_one_attached :image

  validates :image, size: { less_than: 5.megabytes }
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

class Web::Admin::BulletinsController < Web::Admin::ApplicationController
  before_action :authorize_admin

  def index
    @q = Bulletin.ransack(params[:q])
    @bulletins = @q.result(distinct: true).order(created_at: :desc).page params[:page]
  end

  def to_moderate
    bulletin.moderate!
    redirect_to admin_bulletins_path
  end

  def publish
    bulletin.publish!
    redirect_to admin_bulletins_path
  end

  def archive
    bulletin.archive!
    redirect_to admin_bulletins_path
  end

  def reject
    bulletin.reject!
    redirect_to admin_bulletins_path
  end

  private

  def bulletin
    @bulletin ||= Bulletin.find(params[:id])
  end

  def authorize_admin
    authorize %i[admin bulletin]
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

class Web::BulletinsController < Web::ApplicationController
  def index
    @categories = Category.all
    @q = Bulletin.ransack(params[:q])
    @bulletins = @q.result(distinct: true).published.order(created_at: :desc).page params[:page]
  end

  def show
    bulletin
  end

  def new
    authorize [:bulletin]
    @bulletin = Bulletin.new
  end

  def create
    authorize [:bulletin]
    @bulletin = Bulletin.new(user: current_user, **bulletin_params)
    if @bulletin.save
      redirect_to bulletin_path(@bulletin)
    else
      render :new
    end
  end

  def edit
    authorize bulletin
    bulletin
  end

  def update
    authorize bulletin
    if bulletin.update(bulletin_params)
      redirect_to bulletin_path(bulletin)
    else
      render :edit, status: :unprocessible_entity
    end
  end

  def destroy
    authorize bulletin
    bulletin.destroy
    redirect_to request.referer || bulletins_path
  end

  def to_moderate
    authorize bulletin
    if bulletin.may_moderate?
      bulletin.moderate!
      redirect_to profile_path
    else
      render :index, status: :unprocessible_entity
    end
  end

  def archive
    authorize bulletin
    if bulletin.may_archive?
      bulletin.archive!
      redirect_to profile_path
    else
      render :index, status: :unprocessible_entity
    end
  end

  def publish
    authorize bulletin
    bulletin.publish!
    redirect_to request.referer
  end

  def reject
    authorize bulletin
    bulletin.reject!
    redirect_to request.referer
  end

  private

  def bulletin
    @bulletin ||= Bulletin.find(params[:id])
  end

  def bulletin_params
    params.require(:bulletin).permit(:title, :description, :category_id, :image)
  end
end

app/helpers/bulletins_helper.rb
# frozen_string_literal: true

module BulletinsHelper
end

app/views/web/admin/bulletins/index.html.slim
.mb-4
  h2 = t('activerecord.models.bulletin.other')
  hr
= search_form_for @q, url: admin_bulletins_path do |f|
  .row
    .col-sm-6
      = f.search_field :title_cont, class: 'form-control', placeholder: 'Title'
    .col
      = f.select :state_eq, %w[draft rejected published archived under_moderation], { include_blank: t('activerecord.attributes.bulletin.state') }, class: 'form-control'
    .col
      = f.submit class: 'btn btn-primary me-2'
      = link_to t('search.reset'), admin_bulletins_path, class: 'btn btn-outline-primary'

table.table
  thead
    tr
    tr
      th scope="col" = t('activerecord.attributes.bulletin.title')
      th scope="col" = t('activerecord.attributes.bulletin.state')
      th scope="col" = t('activerecord.attributes.bulletin.created_at')
      th scope="col" = t('actions')
  tbody
    - @bulletins.each do |bulletin|
      tr
        td = link_to bulletin.title, bulletin_path(bulletin)
        td = bulletin.state
        td = time_ago_in_words(bulletin.created_at)
        td
          - if bulletin.may_publish?
              = link_to t('bulletins.state.events.approve'), publish_admin_bulletin_path(bulletin), method: :patch, class: 'link-primary me-2'
          - if bulletin.may_reject?
              = link_to t('bulletins.state.events.reject'), reject_admin_bulletin_path(bulletin), method: :patch, class: 'link-danger me-2'
          - if bulletin.may_archive?
              = link_to t('bulletins.state.events.archive'), archive_admin_bulletin_path(bulletin), method: :patch, class: 'link-secondary'
= paginate @bulletins