config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/auth/:provider', to: 'auth#request', as: :auth_request
  get '/auth/:provider/callback', to: 'web/auth#callback', as: :callback_auth

  scope module: :web do
    resources :sessions, only: :destroy
    root 'bulletins#index'
    resources :bulletins do
      member do
        patch 'to_moderate'
        patch 'archive'
      end
    end
    namespace 'admin' do
      root 'bulletins#index'
      resources :bulletins do
        member do
          patch 'to_moderate'
          patch 'publish'
          patch 'archive'
          patch 'reject'
        end
      end
      resources :categories
      resources :users
    end
    get 'profile', to: 'profile#index'
  end
end

app/views/layouts/web/admin/application.html.slim
doctype html
html.h-100
  head
    title
      | Admin panel
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.d-flex.flex-column.h-100
    .container.mb-2
      = render 'layouts/shared/header'
      = render 'layouts/shared/flash' unless flash.empty?
    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .row
              .col-sm-2.border-end
                ul.nav.nav-pills.flex-column.mb-auto
                  li.nav-item
                    = link_to admin_bulletins_path, class: "nav-link link-dark #{'active' if current_page?(admin_bulletins_path)}"
                      <i class="bi bi-file-earmark-fill me-2"></i>
                      | Bulletins
                  li.nav-item
                    = link_to admin_categories_path, class: "nav-link link-dark #{'active' if current_page?(admin_categories_path)}"
                      <i class="bi bi-folder-fill me-2"></i>
                      | Categories
                  li.nav-item
                    = link_to admin_users_path, class: "nav-link link-dark #{'active' if current_page?(admin_users_path)}"
                      <i class="bi bi-people-fill me-2"></i>
                      | Users
              .col-sm-10
                .p-3.p-lg-5.pt-lg-0
                  = yield